site_name: JavaScript Playwright Docs
site_url: https://Play-Wright-course.github.io/Java-Script-Doc/
use_directory_urls: true
nav:
  - Home: index.md
  - JavaScript Concepts:
      - Variables: javascriptConcepts/variables.md
      - Data Types: javascriptConcepts/dataTypes.md
      - Operators: javascriptConcepts/operator.md
      - Flow Statements: javascriptConcepts/flow-statement.md
      - Functions: javascriptConcepts/functions.md
      - Arrays & Objects: javascriptConcepts/Arrays.md
      
  - PlayWright With Java:
      - Locators: playwright-Java/locator.md
      - PlayWright interactions:
          - Inputs/Buttons: playwright-Java/playwright-interaction.md
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - tables


