site_name: JavaScript Playwright Docs
site_url: https://usonawane/js-playwright-doc
use_directory_urls: true
nav:
  - Home: index.md
  - JavaScript Concepts:
      - Variables: javascriptConcepts/variables.md
      - Data Types: javascriptConcepts/dataTypes.md
      - Operators: javascriptConcepts/operator.md
      - Flow Statements: javascriptConcepts/flow-statement.md
      - Functions: javascriptConcepts/functions.md
      - Arrays & Objects: javascriptConcepts/Arrays.md

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - tables
