version: '3'

services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: jsdocs
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
      - ./mkdocs.yml:/mkdocs.yml
    command: ["mkdocs", "serve", "--dev-addr=0.0.0.0:8000"]
